In [ ]:
!pip install pandas numpy scikit-learn matplotlib seaborn plotly

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (2.0.2)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (1.6.1)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.12/dist-packages (3.10.0)
Requirement already satisfied: seaborn in /usr/local/lib/python3.12/dist-packages (0.13.2)
Requirement already satisfied: plotly in /usr/local/lib/python3.12/dist-packages (5.24.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.1)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (4.62.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (26.1)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (3.3.2)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.12/dist-packages (from plotly) (9.1.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
# Load datasets

courses = pd.read_csv("/content/Courses.csv")
teachers = pd.read_csv("/content/ Teachers.csv")
transactions = pd.read_csv("/content/Transactions.csv")
users = pd.read_csv("/content/ Users.csv")

In [ ]:
print("COURSES DATA")
display(courses.head())

print("TEACHERS DATA")
display(teachers.head())

print("TRANSACTIONS DATA")
display(transactions.head())

print("USERS DATA")
display(users.head())

COURSES DATA

,CourseID,CourseName,CourseCategory,CourseType,CourseLevel,CoursePrice,CourseDuration,CourseRating
0,CR00001,Python Basics,Programming,Paid,Beginner,472.28,11.00,4.74
1,CR00002,Java Programming,Programming,Free,Intermediate,0.00,37.70,2.43
2,CR00003,C++ for Beginners,Programming,Free,Beginner,0.00,19.53,3.85
3,CR00004,Advanced Python,Programming,Free,Beginner,0.00,45.13,2.88
4,CR00005,Full Stack Development,Programming,Free,Beginner,0.00,28.68,1.28

TEACHERS DATA

,TeacherID,TeacherName,Age,Gender,Expertise,YearsOfExperience,TeacherRating
0,TC00001,Leonard Montgomery,44,Female,Cybersecurity,6,3.24
1,TC00002,Jill Day,32,Female,Digital Marketing,9,4.14
2,TC00003,Amber Torres,32,Male,Design,4,1.56
3,TC00004,Kristi Scott,34,Female,Machine Learning,9,4.39
4,TC00005,David Williams,34,Male,Finance,2,3.11

TRANSACTIONS DATA

,TransactionID,UserID,CourseID,TransactionDate,Amount,PaymentMethod,TeacherID
0,TT00001,U00003,CR00016,25/10/2025,0.0,PayPal,TC00040
1,TT00002,U00003,CR00037,13/1/2025,0.0,PayPal,TC00040
2,TT00003,U00003,CR00019,28/3/2025,0.0,Bank Transfer,TC00040
3,TT00004,U00004,CR00048,2/6/2025,0.0,Bank Transfer,TC00040
4,TT00005,U00004,CR00060,10/8/2025,0.0,PayPal,TC00042

USERS DATA

   UserID        UserName  Age  Gender                             Email
0  U00001    wilsonjordan   15    Male            patricia27@hotmail.com
1  U00002        angela22   29  Female             hallrandy@hotmail.com
2  U00003  morrisonamanda   33  Female               ganderson@yahoo.com
3  U00004       fthornton   23  Female  christensencatherine@outlook.com
4  U00005  fostergeoffrey   21    Male            karenfuentes@yahoo.com

In [ ]:
print("COURSES COLUMNS")
print(courses.columns)

print("\nTEACHERS COLUMNS")
print(teachers.columns)

print("\nTRANSACTIONS COLUMNS")
print(transactions.columns)

print("\nUSERS COLUMNS")
print(users.columns)

COURSES COLUMNS
Index(['CourseID', 'CourseName', 'CourseCategory', 'CourseType', 'CourseLevel',
       'CoursePrice', 'CourseDuration', 'CourseRating'],
      dtype='object')

TEACHERS COLUMNS
Index(['TeacherID', 'TeacherName', 'Age', 'Gender', 'Expertise',
       'YearsOfExperience', 'TeacherRating'],
      dtype='object')

TRANSACTIONS COLUMNS
Index(['TransactionID', 'UserID', 'CourseID', 'TransactionDate', 'Amount',
       'PaymentMethod', 'TeacherID'],
      dtype='object')

USERS COLUMNS
Index(['UserID', 'UserName', 'Age', 'Gender', 'Email'], dtype='object')

In [ ]:
# Merge Courses with Transactions

merged_data = pd.merge(
    courses,
    transactions,
    on="CourseID",
    how="left"
)

# Merge with Teachers

merged_data = pd.merge(
    merged_data,
    teachers,
    on="TeacherID",
    how="left"
)

# Merge with Users

merged_data = pd.merge(
    merged_data,
    users,
    on="UserID",
    how="left"
)

# Display merged dataset

print("MERGED DATASET")
display(merged_data.head())

MERGED DATASET

,CourseID,CourseName,CourseCategory,CourseType,CourseLevel,CoursePrice,CourseDuration,CourseRating,TransactionID,UserID,...,TeacherName,Age_x,Gender_x,Expertise,YearsOfExperience,TeacherRating,UserName,Age_y,Gender_y,Email
0,CR00001,Python Basics,Programming,Paid,Beginner,472.28,11.0,4.74,TT00021,U00018,...,Yolanda Levine,49,Female,Machine Learning,21,4.97,nicole97,24,Female,aprilharrell@hotmail.com
1,CR00001,Python Basics,Programming,Paid,Beginner,472.28,11.0,4.74,TT00061,U00117,...,Kimberly Miller,49,Male,Cybersecurity,24,4.58,kristin26,19,Female,megan10@gmail.com
2,CR00001,Python Basics,Programming,Paid,Beginner,472.28,11.0,4.74,TT00085,U00147,...,Yolanda Levine,49,Female,Machine Learning,21,4.97,patricklaura,30,Male,barbarapatterson@yahoo.com
3,CR00001,Python Basics,Programming,Paid,Beginner,472.28,11.0,4.74,TT00090,U00152,...,Yolanda Levine,49,Female,Machine Learning,21,4.97,hhill,19,Female,keith03@outlook.com
4,CR00001,Python Basics,Programming,Paid,Beginner,472.28,11.0,4.74,TT00144,U00238,...,Kimberly Miller,49,Male,Cybersecurity,24,4.58,joshuaescobar,24,Female,isaiahwest@outlook.com

In [ ]:
print("Dataset Shape:")
print(merged_data.shape)

Dataset Shape:
(10000, 24)

In [ ]:
print("Missing Values:")
print(merged_data.isnull().sum())

Missing Values:
CourseID             0
CourseName           0
CourseCategory       0
CourseType           0
CourseLevel          0
CoursePrice          0
CourseDuration       0
CourseRating         0
TransactionID        0
UserID               0
TransactionDate      0
Amount               0
PaymentMethod        0
TeacherID            0
TeacherName          0
Age_x                0
Gender_x             0
Expertise            0
YearsOfExperience    0
TeacherRating        0
UserName             0
Age_y                0
Gender_y             0
Email                0
dtype: int64

In [ ]:
# Fill missing ratings with average values

merged_data["CourseRating"].fillna(
    merged_data["CourseRating"].mean(),
    inplace=True
)

merged_data["TeacherRating"].fillna(
    merged_data["TeacherRating"].mean(),
    inplace=True
)

# Remove remaining null rows

merged_data.dropna(inplace=True)

# Verify cleaning

print("Missing Values After Cleaning:")
print(merged_data.isnull().sum())

Missing Values After Cleaning:
CourseID             0
CourseName           0
CourseCategory       0
CourseType           0
CourseLevel          0
CoursePrice          0
CourseDuration       0
CourseRating         0
TransactionID        0
UserID               0
TransactionDate      0
Amount               0
PaymentMethod        0
TeacherID            0
TeacherName          0
Age_x                0
Gender_x             0
Expertise            0
YearsOfExperience    0
TeacherRating        0
UserName             0
Age_y                0
Gender_y             0
Email                0
dtype: int64

/tmp/ipykernel_3070/215533839.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_data["CourseRating"].fillna(
/tmp/ipykernel_3070/215533839.py:8: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_data["TeacherRating"].fillna(

In [ ]:
# Create Revenue column

merged_data["Revenue"] = merged_data["Amount"]

# Display updated dataset

display(merged_data.head())

,CourseID,CourseName,CourseCategory,CourseType,CourseLevel,CoursePrice,CourseDuration,CourseRating,TransactionID,UserID,...,Age_x,Gender_x,Expertise,YearsOfExperience,TeacherRating,UserName,Age_y,Gender_y,Email,Revenue
0,CR00001,Python Basics,Programming,Paid,Beginner,472.28,11.0,4.74,TT00021,U00018,...,49,Female,Machine Learning,21,4.97,nicole97,24,Female,aprilharrell@hotmail.com,472.28
1,CR00001,Python Basics,Programming,Paid,Beginner,472.28,11.0,4.74,TT00061,U00117,...,49,Male,Cybersecurity,24,4.58,kristin26,19,Female,megan10@gmail.com,472.28
2,CR00001,Python Basics,Programming,Paid,Beginner,472.28,11.0,4.74,TT00085,U00147,...,49,Female,Machine Learning,21,4.97,patricklaura,30,Male,barbarapatterson@yahoo.com,472.28
3,CR00001,Python Basics,Programming,Paid,Beginner,472.28,11.0,4.74,TT00090,U00152,...,49,Female,Machine Learning,21,4.97,hhill,19,Female,keith03@outlook.com,472.28
4,CR00001,Python Basics,Programming,Paid,Beginner,472.28,11.0,4.74,TT00144,U00238,...,49,Male,Cybersecurity,24,4.58,joshuaescobar,24,Female,isaiahwest@outlook.com,472.28

In [ ]:
# Create Price Bands

merged_data["PriceBand"] = pd.cut(
    merged_data["CoursePrice"],
    bins=[0, 1000, 3000, 10000],
    labels=["Low", "Medium", "High"]
)

display(merged_data[["CoursePrice", "PriceBand"]].head())

   CoursePrice PriceBand
0       472.28       Low
1       472.28       Low
2       472.28       Low
3       472.28       Low
4       472.28       Low

In [ ]:
# Experience Buckets

merged_data["ExperienceLevel"] = pd.cut(
    merged_data["YearsOfExperience"],
    bins=[0, 3, 7, 20],
    labels=["Beginner", "Intermediate", "Expert"]
)

display(
    merged_data[
        ["YearsOfExperience", "ExperienceLevel"]
    ].head()
)

   YearsOfExperience ExperienceLevel
0                 21             NaN
1                 24             NaN
2                 21             NaN
3                 21             NaN
4                 24             NaN

In [ ]:
# Rating Tiers

merged_data["RatingTier"] = pd.cut(
    merged_data["CourseRating"],
    bins=[0, 3.5, 4.5, 5],
    labels=["Average", "Good", "Excellent"]
)

display(
    merged_data[
        ["CourseRating", "RatingTier"]
    ].head()
)

   CourseRating RatingTier
0          4.74  Excellent
1          4.74  Excellent
2          4.74  Excellent
3          4.74  Excellent
4          4.74  Excellent

In [ ]:
# Enrollment count per course

enrollment_counts = merged_data.groupby(
    "CourseID"
).size()

# Map counts back

merged_data["EnrollmentCount"] = merged_data[
    "CourseID"
].map(enrollment_counts)

display(
    merged_data[
        ["CourseID", "EnrollmentCount"]
    ].head()
)

  CourseID  EnrollmentCount
0  CR00001              164
1  CR00001              164
2  CR00001              164
3  CR00001              164
4  CR00001              164

In [ ]:
# Save processed dataset

merged_data.to_csv(
    "merged_data.csv",
    index=False
)

print("Processed dataset saved successfully!")

Processed dataset saved successfully!

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [ ]:
# Create label encoder

encoder = LabelEncoder()

# Encode categorical columns

merged_data["CourseCategory"] = encoder.fit_transform(
    merged_data["CourseCategory"]
)

merged_data["CourseLevel"] = encoder.fit_transform(
    merged_data["CourseLevel"]
)

merged_data["CourseType"] = encoder.fit_transform(
    merged_data["CourseType"]
)

merged_data["PriceBand"] = encoder.fit_transform(
    merged_data["PriceBand"]
)

merged_data["ExperienceLevel"] = encoder.fit_transform(
    merged_data["ExperienceLevel"]
)

merged_data["RatingTier"] = encoder.fit_transform(
    merged_data["RatingTier"]
)

print("Encoding completed!")

Encoding completed!

In [ ]:
# Input features

X = merged_data[
    [
        "CourseCategory",
        "CourseType",
        "CourseLevel",
        "CoursePrice",
        "CourseDuration",
        "CourseRating",
        "TeacherRating",
        "YearsOfExperience",
        "PriceBand",
        "ExperienceLevel",
        "RatingTier"
    ]
]

# Target variable

y = merged_data["EnrollmentCount"]

print(X.head())

   CourseCategory  CourseType  CourseLevel  CoursePrice  CourseDuration  \
0               9           1            1       472.28            11.0
1               9           1            1       472.28            11.0
2               9           1            1       472.28            11.0
3               9           1            1       472.28            11.0
4               9           1            1       472.28            11.0

   CourseRating  TeacherRating  YearsOfExperience  PriceBand  ExperienceLevel  \
0          4.74           4.97                 21          0                3
1          4.74           4.58                 24          0                3
2          4.74           4.97                 21          0                3
3          4.74           4.97                 21          0                3
4          4.74           4.58                 24          0                3

   RatingTier
0           1
1           1
2           1
3           1
4           1

In [ ]:
# Split dataset

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

print("Training Data Shape:", X_train.shape)
print("Testing Data Shape:", X_test.shape)

Training Data Shape: (8000, 11)
Testing Data Shape: (2000, 11)

In [ ]:
# Create model

model = LinearRegression()

# Train model

model.fit(X_train, y_train)

print("Model trained successfully!")

Model trained successfully!

In [ ]:
# Predict enrollments

predictions = model.predict(X_test)

print(predictions[:5])

[165.47710533 165.05451045 162.25389353 164.57528485 175.00202587]

In [ ]:
# Evaluation metrics

mae = mean_absolute_error(y_test, predictions)

rmse = mean_squared_error(
    y_test,
    predictions
) ** 0.5

r2 = r2_score(y_test, predictions)

print("MAE:", mae)
print("RMSE:", rmse)
print("R2 Score:", r2)

MAE: 8.436623338087228
RMSE: 10.413362100968387
R2 Score: 0.28624062357719704

In [ ]:
results = pd.DataFrame({
    "Actual": y_test,
    "Predicted": predictions
})

display(results.head(10))

      Actual   Predicted
6252     158  165.477105
4684     155  165.054510
1731     151  162.253894
4742     155  164.575285
4521     171  175.002026
6340     167  162.210914
576      154  160.601164
5202     163  167.772809
6363     167  162.277624
439      173  178.180830

In [ ]:
importance = pd.DataFrame({
    "Feature": X.columns,
    "Importance": model.coef_
})

importance = importance.sort_values(
    by="Importance",
    ascending=False
)

display(importance)

              Feature  Importance
10         RatingTier    6.670935
8           PriceBand    0.552623
5        CourseRating    0.276090
7   YearsOfExperience    0.051169
3         CoursePrice   -0.011726
6       TeacherRating   -0.044715
4      CourseDuration   -0.148400
9     ExperienceLevel   -0.261028
0      CourseCategory   -0.331289
1          CourseType   -0.552623
2         CourseLevel   -1.206728

In [ ]:
import joblib

# Save model

joblib.dump(
    model,
    "forecast_model.pkl"
)

print("Model saved successfully!")

Model saved successfully!

In [ ]:
import pandas as pd

# ==============================
# LOAD DATASETS
# ==============================

courses = pd.read_csv("/content/Courses.csv")
teachers = pd.read_csv("/content/ Teachers.csv")
transactions = pd.read_csv("/content/Transactions.csv")
users = pd.read_csv("/content/ Users.csv")
# ==============================
# DISPLAY DATA
# ==============================

print("\nCOURSES DATA")
print(courses.head())

print("\nTEACHERS DATA")
print(teachers.head())

print("\nTRANSACTIONS DATA")
print(transactions.head())

print("\nUSERS DATA")
print(users.head())

# ==============================
# MERGE DATASETS
# ==============================

# Merge Courses + Transactions
merged_data = pd.merge(
    courses,
    transactions,
    on="CourseID",
    how="left"
)

# Merge with Teachers
merged_data = pd.merge(
    merged_data,
    teachers,
    on="TeacherID",
    how="left"
)

# Merge with Users
merged_data = pd.merge(
    merged_data,
    users,
    on="UserID",
    how="left"
)

# ==============================
# CHECK MERGED DATA
# ==============================

print("\nMERGED DATASET")
print(merged_data.head())

print("\nDATASET SHAPE")
print(merged_data.shape)

# ==============================
# CHECK MISSING VALUES
# ==============================

print("\nMISSING VALUES")
print(merged_data.isnull().sum())

# ==============================
# HANDLE MISSING VALUES
# ==============================

merged_data["CourseRating"] = merged_data[
    "CourseRating"
].fillna(
    merged_data["CourseRating"].mean()
)

merged_data["TeacherRating"] = merged_data[
    "TeacherRating"
].fillna(
    merged_data["TeacherRating"].mean()
)

merged_data.dropna(inplace=True)

# ==============================
# CREATE REVENUE COLUMN
# ==============================

merged_data["Revenue"] = merged_data["Amount"]

# ==============================
# PRICE BANDS
# ==============================

merged_data["PriceBand"] = pd.cut(
    merged_data["CoursePrice"],
    bins=[0, 1000, 3000, 10000],
    labels=["Low", "Medium", "High"]
)

# ==============================
# EXPERIENCE LEVELS
# ==============================

merged_data["ExperienceLevel"] = pd.cut(
    merged_data["YearsOfExperience"],
    bins=[0, 3, 7, 20],
    labels=["Beginner", "Intermediate", "Expert"]
)

# ==============================
# RATING TIERS
# ==============================

merged_data["RatingTier"] = pd.cut(
    merged_data["CourseRating"],
    bins=[0, 3.5, 4.5, 5],
    labels=["Average", "Good", "Excellent"]
)

# ==============================
# ENROLLMENT COUNT
# ==============================

enrollment_counts = merged_data.groupby(
    "CourseID"
).size()

merged_data["EnrollmentCount"] = merged_data[
    "CourseID"
].map(enrollment_counts)

# ==============================
# SAVE FINAL DATASET
# ==============================
merged_data.to_csv(
    "merged_data.csv",
    index=False
)
print("\nDATA PREPROCESSING COMPLETED SUCCESSFULLY!")

COURSES DATA
  CourseID              CourseName CourseCategory CourseType   CourseLevel  \
0  CR00001           Python Basics    Programming       Paid      Beginner
1  CR00002        Java Programming    Programming       Free  Intermediate
2  CR00003       C++ for Beginners    Programming       Free      Beginner
3  CR00004         Advanced Python    Programming       Free      Beginner
4  CR00005  Full Stack Development    Programming       Free      Beginner

   CoursePrice  CourseDuration  CourseRating
0       472.28           11.00          4.74
1         0.00           37.70          2.43
2         0.00           19.53          3.85
3         0.00           45.13          2.88
4         0.00           28.68          1.28

TEACHERS DATA
  TeacherID         TeacherName  Age  Gender          Expertise  \
0   TC00001  Leonard Montgomery   44  Female      Cybersecurity
1   TC00002            Jill Day   32  Female  Digital Marketing
2   TC00003        Amber Torres   32    Male             Design
3   TC00004        Kristi Scott   34  Female   Machine Learning
4   TC00005      David Williams   34    Male            Finance

   YearsOfExperience  TeacherRating
0                  6           3.24
1                  9           4.14
2                  4           1.56
3                  9           4.39
4                  2           3.11

TRANSACTIONS DATA
  TransactionID  UserID CourseID TransactionDate  Amount  PaymentMethod  \
0       TT00001  U00003  CR00016      25/10/2025     0.0         PayPal
1       TT00002  U00003  CR00037       13/1/2025     0.0         PayPal
2       TT00003  U00003  CR00019       28/3/2025     0.0  Bank Transfer
3       TT00004  U00004  CR00048        2/6/2025     0.0  Bank Transfer
4       TT00005  U00004  CR00060       10/8/2025     0.0         PayPal

  TeacherID
0   TC00040
1   TC00040
2   TC00040
3   TC00040
4   TC00042

USERS DATA
   UserID        UserName  Age  Gender                             Email
0  U00001    wilsonjordan   15    Male            patricia27@hotmail.com
1  U00002        angela22   29  Female             hallrandy@hotmail.com
2  U00003  morrisonamanda   33  Female               ganderson@yahoo.com
3  U00004       fthornton   23  Female  christensencatherine@outlook.com
4  U00005  fostergeoffrey   21    Male            karenfuentes@yahoo.com

MERGED DATASET
  CourseID     CourseName CourseCategory CourseType CourseLevel  CoursePrice  \
0  CR00001  Python Basics    Programming       Paid    Beginner       472.28
1  CR00001  Python Basics    Programming       Paid    Beginner       472.28
2  CR00001  Python Basics    Programming       Paid    Beginner       472.28
3  CR00001  Python Basics    Programming       Paid    Beginner       472.28
4  CR00001  Python Basics    Programming       Paid    Beginner       472.28

   CourseDuration  CourseRating TransactionID  UserID  ...      TeacherName  \
0            11.0          4.74       TT00021  U00018  ...   Yolanda Levine
1            11.0          4.74       TT00061  U00117  ...  Kimberly Miller
2            11.0          4.74       TT00085  U00147  ...   Yolanda Levine
3            11.0          4.74       TT00090  U00152  ...   Yolanda Levine
4            11.0          4.74       TT00144  U00238  ...  Kimberly Miller

   Age_x Gender_x         Expertise YearsOfExperience  TeacherRating  \
0     49   Female  Machine Learning                21           4.97
1     49     Male     Cybersecurity                24           4.58
2     49   Female  Machine Learning                21           4.97
3     49   Female  Machine Learning                21           4.97
4     49     Male     Cybersecurity                24           4.58

        UserName Age_y  Gender_y                       Email
0       nicole97    24    Female    aprilharrell@hotmail.com
1      kristin26    19    Female           megan10@gmail.com
2   patricklaura    30      Male  barbarapatterson@yahoo.com
3          hhill    19    Female         keith03@outlook.com
4  joshuaescobar    24    Female      isaiahwest@outlook.com

[5 rows x 24 columns]

DATASET SHAPE
(10000, 24)

MISSING VALUES
CourseID             0
CourseName           0
CourseCategory       0
CourseType           0
CourseLevel          0
CoursePrice          0
CourseDuration       0
CourseRating         0
TransactionID        0
UserID               0
TransactionDate      0
Amount               0
PaymentMethod        0
TeacherID            0
TeacherName          0
Age_x                0
Gender_x             0
Expertise            0
YearsOfExperience    0
TeacherRating        0
UserName             0
Age_y                0
Gender_y             0
Email                0
dtype: int64

DATA PREPROCESSING COMPLETED SUCCESSFULLY!